In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    #layer 1

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    #layer 2
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [ ]:
features = torch.rand(10,5)

In [ ]:
features

tensor([[0.9003, 0.6027, 0.1436, 0.9594, 0.3056],
        [0.9170, 0.8072, 0.2083, 0.9666, 0.8368],
        [0.7453, 0.5068, 0.1927, 0.1723, 0.3564],
        [0.2673, 0.9867, 0.1880, 0.8319, 0.0470],
        [0.1809, 0.8528, 0.9771, 0.9727, 0.9709],
        [0.2115, 0.0428, 0.4096, 0.4787, 0.5826],
        [0.8000, 0.3365, 0.7748, 0.0633, 0.5415],
        [0.1936, 0.9744, 0.5605, 0.3167, 0.1150],
        [0.8760, 0.0244, 0.3389, 0.3732, 0.6946],
        [0.9570, 0.2061, 0.5052, 0.3842, 0.0777]])

In [ ]:
model = Model(features.shape[1])

In [ ]:
model(features)

tensor([[0.4935],
        [0.4862],
        [0.5114],
        [0.5156],
        [0.5024],
        [0.4910],
        [0.5203],
        [0.5347],
        [0.4979],
        [0.5165]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.network[0].weight

Parameter containing:
tensor([[ 0.3066, -0.2221, -0.1093,  0.4287,  0.4326],
        [ 0.4463, -0.3794, -0.0705,  0.1214,  0.0953],
        [ 0.2600,  0.3808,  0.3800, -0.1111,  0.0786]], requires_grad=True)

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [12]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [14]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [16]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [20]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_6131/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_6131/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_6131/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_6131/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [21]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [22]:
torch.rand(30,1)

tensor([[0.4700],
        [0.7069],
        [0.1874],
        [0.7122],
        [0.8702],
        [0.7677],
        [0.4013],
        [0.9155],
        [0.8070],
        [0.8697],
        [0.1393],
        [0.6089],
        [0.8441],
        [0.8892],
        [0.5620],
        [0.9119],
        [0.6381],
        [0.6690],
        [0.0982],
        [0.4959],
        [0.7762],
        [0.3986],
        [0.8446],
        [0.6329],
        [0.0978],
        [0.9572],
        [0.0343],
        [0.1411],
        [0.0749],
        [0.5548]])

In [23]:
X_train_tensor.shape[1]

30

In [24]:
learning_rate = 0.1
epochs = 25

In [25]:
loss_function = nn.BCELoss()

In [26]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [27]:
model = MySimpleNN(X_train_tensor.shape[1])

In [32]:
model.parameters()

In [33]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

   #zero gradient
  optimizer.zero_grad()


  #backward pass
  loss.backward()


  #parameter update
  optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.6246396899223328
 2 , Loss = 0.4784642159938812
 3 , Loss = 0.40134772658348083
 4 , Loss = 0.35403525829315186
 5 , Loss = 0.32159423828125
 6 , Loss = 0.29764461517333984
 7 , Loss = 0.2790471315383911
 8 , Loss = 0.26407068967819214
 9 , Loss = 0.25167545676231384
 10 , Loss = 0.24119515717029572
 11 , Loss = 0.23218098282814026
 12 , Loss = 0.22431854903697968
 13 , Loss = 0.21738019585609436
 14 , Loss = 0.21119673550128937
 15 , Loss = 0.20563943684101105
 16 , Loss = 0.20060838758945465
 17 , Loss = 0.19602473080158234
 18 , Loss = 0.19182534515857697
 19 , Loss = 0.1879590004682541
 20 , Loss = 0.18438351154327393
 21 , Loss = 0.1810639500617981
 22 , Loss = 0.17797093093395233
 23 , Loss = 0.17507974803447723
 24 , Loss = 0.17236922681331635
 25 , Loss = 0.16982126235961914

In [34]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6046475768089294

In [35]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================